### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by atomczak** [atomczak/ChatBotGame#5]
Error contents:
`  File "/home/RockPaperScissors/code/rock_paper_scissors.py", line 46, in play_a_round
    except socket.error as e:
NameError: name 'socket' is not defined`
and:
`mysql.connector.errors.OperationalError: 2055: Lost connection to MySQL server at 'RockPaperScissors.mysql.pythonanywhere-services.com:3306', system error: 32 Broken pipe`
and:
`BrokenPipeError: [Errno 32] Broken pipe`

Trigger words: "Play" and "Start"

**Comment by JTurbakiewicz** [comment]
Probable cause: connection timeout
Proposed solution: settting up and closing the connection with each query. If that proves to be slow, I'll reestablish the connection anytime it gets timeouted.

**Comment by JTurbakiewicz** [comment]
Not closing yet, if it works for you on the server, please close.
